///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class AppImages {
  AppImages._();

  static const String imagesBackGroundSplashLight = 'assets/images/back_ground_splash_light.png';
  static const String imagesSplashLogo12 = 'assets/images/splash_logo_12+.png';
  static const String imagesWelcomeBackGround = 'assets/images/welcome_back_ground.png';
  static const String imageSplashLogo = 'assets/images/image_splash_logo.png';

}
